// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3d0yRYcHbfqtvJ16mnZC6Jpd9bk1pmbQ',
    appId: '1:685333552471:web:1c5f4b43644b395ebe3212',
    messagingSenderId: '685333552471',
    projectId: 'pmsn20252v',
    authDomain: 'pmsn20252v.firebaseapp.com',
    storageBucket: 'pmsn20252v.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiyDN63ZsKxeUL1ZObliDrMYhlzRaSf3A',
    appId: '1:685333552471:android:6c393925a667630abe3212',
    messagingSenderId: '685333552471',
    projectId: 'pmsn20252v',
    storageBucket: 'pmsn20252v.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqFTQoae2eBzRu6lhN7P0yHc9R2ocVYs',
    appId: '1:685333552471:ios:bd6b830215e9aeb0be3212',
    messagingSenderId: '685333552471',
    projectId: 'pmsn20252v',
    storageBucket: 'pmsn20252v.firebasestorage.app',
    iosBundleId: 'com.example.pmsn20252',
  );

}